### ISSUE TITLE
Google Drive Service Account Credential Not Working

### ISSUE THREAD

**Issue by mdt1024** [Smarteon/puppet-rclone#6]
Hi,

I've tried many combinations of embedding the json service account credential in a profile manifest and hiera yaml file, trying heredoc in the manifest like so:

>$service_account_credential = @(CREDENTIAL:json /L)
    {"type": "service_account",
  "project_id": "rclone-12345",
   [...]}
   | - CREDENTIAL 

or in the hiera yaml file like:

>
--
role: backup
rclone::gdrive::os_user: root
rclone::gdrive::config_name: googledrive
rclone::gdrive::client_id: '1234'
rclone::gdrive::client_secret: ''
rclone::gdrive::team_drive: teamdrive
rclone::gdrive::root_folder_id: asdflkasdjflskdfjasldkj-
rclone::gdrive::scope: drive
rclone::gdrive::service_account_credentials: >
  {type: 'service_account',
    project_id: 'rclone-12345',
    private_key_id: 'alsdjflkasdjflkasdjfl;askdjf;lasdjfa;lsdkjfsdl',
    private_key: "-----BEGIN PRIVATE KEY-----\n[...]\n-----END PRIVATE KEY-----\n",
    client_email: 'rcloneemail@google.com',
    client_id: '1234',
    auth_uri: 'https://accounts.google.com/o/oauth2/auth',
    token_uri: 'https://oauth2.googleapis.com/token',
    auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs',
    client_x509_cert_url: 'https://somegoogleurl'}

In either case, the error output from a puppet client linux host is as follows:

> me@host:~$ sudo /opt/puppetlabs/bin/puppet agent --test --environment=myenvironment
Info: Using configured environment 'myenvironment'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for backup.lygos.com
Info: Applying configuration version 'puppet-myenvironment-1234'
Notice: Hiera returned role: backup
Notice: /Stage[main]/Main/Notify[Hiera returned role: backup]/message: defined 'message' as 'Hiera returned role: backup'
Notice: /Stage[main]/Nrpe::Install/Package[nagios-plugins]/ensure: created (corrective)
**Error: Could not find command '\ \ \"project_id\":\ \"rclone-12345\",'**
**Error: /Stage[main]/Profile::Backup/Rclone::Config::Gdrive[drive_remote]/Rclone::Config[googledrive]/Exec[rclone create remote googledrive for user root]/returns: change from 'notrun' to ['0'] failed: Could not find command '\ \ \"project_id\":\ \"rclone-12345\",' (corrective)**

Not sure why it appears that puppet is attempting to exec a command formed by the string \ \ \"project_id\":\ \"rclone-12345\",' (?).

An example of how to embed the service_account_credentials in either a manifest or hiera file would be most welcome.
I know that the credentials work when I manually install them on a host and run rclone to Google Drive.

Thanks for your work on the rclone module!

Marshall

**Comment by jimirocks** [comment]
Hi, to be honest this part is not well tested, the problem here is, that configuration options are basically concatened to the shell call of `rclone config` - see here https://github.com/Smarteon/puppet-rclone/blob/master/manifests/config.pp#L79

This implies the credentails JSON must be properly escaped as you would like to write it in bash command line.

Definitely there is a space for improvement - contribution is welcomed.

**Comment by mdt1024** [comment]
You rock jimirocks!

That was enough of a hint to get me to an answer.  Sadly I don't know Ruby, so I can't really contribute to the code, but this is a an example of how I got a working $service_account_credential in my manifest:

class profile::backup {
  class { 'rclone':
      ensure => '1.59.2'
  }
  $service_account_credential = '{ "type": "service_account", "project_id": "rclone-12345", "private_key_id": "c5f6ebf4sdfjksdjfljsdlfkjskdjf39fdea", "private_key": "-----BEGIN PRIVATE KEY-----\\n[YOUR BIG UGLY PRIVATE KEY]\\n-----END PRIVATE KEY-----\\n", "client_email": "rclone-service@rclone-12345.iam.gserviceaccount.com", "client_id": "12345678912345678912", "auth_uri": "https://accounts.google.com/o/oauth2/auth", "token_uri": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/therestofthatURL.com" }'

>  rclone::config::gdrive { 'drive_remote':
      scope                       => 'drive',
      os_user                     => 'root',
      root_folder_id              => 'asdlkfjsdlfjslslkdfsdfjldksjfalsjC-',
      config_name                 => 'googledrive',
      client_id                   => '12345678912345678912',
      client_secret               => '',
      service_account_credentials => $service_account_credential
  }
}

Hope this helps someone else!

**Comment by jimirocks** [comment]
I am glad you figured it out!
